# Generated by Django 2.1.5 on 2019-02-04 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionRopa', '0005_auto_20190128_1329'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Preguntas', '0001_initial'),
    ]


