# Generated by Django 2.1.5 on 2019-02-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0002_auto_20190204_0918'),
    ]

