# Generated by Django 2.1.5 on 2019-02-04 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0003_auto_20190204_0923'),
    ]


