# Generated by Django 2.1.5 on 2019-02-04 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GestionRopa', '0005_auto_20190128_1329'),
        ('Preguntas', '0004_auto_20190204_0930'),
    ]

  
