# Generated by Django 2.1.5 on 2019-01-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionRopa', '0002_auto_20190128_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='ropa',
            name='Talla',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='talla'),
        ),
    ]
