# Generated by Django 2.1.5 on 2019-01-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionRopa', '0003_auto_20190128_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ropa',
            old_name='User',
            new_name='user',
        ),
    ]
