# Generated by Django 2.1.5 on 2019-01-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionRopa', '0004_auto_20190128_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='imagen'),
        ),
    ]
