# Generated by Django 2.1.5 on 2019-01-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50, verbose_name='titulo')),
                ('Resumen', models.CharField(max_length=300, verbose_name='resumen')),
                ('Cuerpo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='cuerpo')),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='imagen')),
            ],
        ),
    ]
