# Generated by Django 2.1.5 on 2019-02-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competiciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competiciones',
            options={'verbose_name': 'Competicion', 'verbose_name_plural': 'Competiciones'},
        ),
    ]
