# Generated by Django 2.1.5 on 2019-02-13 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competiciones', '0002_auto_20190213_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('Competiciones', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competiciones.Competiciones', verbose_name='competiciones')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
