# Generated by Django 2.1.5 on 2019-02-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competiciones', '0003_participaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participaciones',
            options={'verbose_name': 'Participacion', 'verbose_name_plural': 'Participaciones'},
        ),
    ]
