# Generated by Django 2.1.5 on 2019-02-15 20:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competiciones', '0004_auto_20190213_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competiciones',
            name='Descripcion',
            field=ckeditor.fields.RichTextField(max_length=900, verbose_name='descripcion'),
        ),
    ]
