# Generated by Django 2.1.5 on 2019-02-15 20:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competiciones', '0005_auto_20190215_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competiciones',
            name='Descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=900, verbose_name='descripcion'),
        ),
    ]
